# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-22 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doniServer', '0129_auto_20170721_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_no', models.IntegerField(default=1)),
                ('date', models.DateField()),
                ('port_clearing_no', models.CharField(max_length=50, null=True)),
                ('fcl_quantity', models.IntegerField(default=0.0)),
                ('positive', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doniServer.Products')),
                ('transaction_business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doniServer.BpBasic')),
            ],
            options={
                'db_table': 'inventory_transaction',
            },
        ),
        migrations.CreateModel(
            name='InventoryTransactionTruckFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('truck_no', models.CharField(max_length=100, null=True)),
                ('weight_in_kg', models.FloatField(default=0.0)),
                ('remarks', models.TextField(null=True)),
            ],
            options={
                'db_table': 'inventory_transaction_truck_flow',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lots', models.IntegerField(default=0)),
                ('address', models.TextField()),
                ('contact', models.TextField()),
                ('self_warehouse', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'inventory_warehouse',
            },
        ),
        migrations.CreateModel(
            name='WarehouseRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_change', models.DateField()),
                ('rate', models.FloatField(default=0.0)),
                ('currency', models.CharField(max_length=5)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doniInventory.Warehouse')),
            ],
            options={
                'db_table': 'inventory_warehouse_rent',
            },
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doniInventory.Warehouse'),
        ),
    ]
