# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-24 10:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doniInventory', '0002_auto_20170723_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouserent',
            old_name='rate',
            new_name='rent',
        ),
        migrations.AddField(
            model_name='warehouserent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='warehouserent',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_rent_created_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouserent',
            name='data_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='warehouserent',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='warehouserent',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_rent_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
