# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-24 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doniInventory', '0003_auto_20170724_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouserent',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_rent', to='doniInventory.Warehouse'),
        ),
    ]
