# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doniInventory', '0005_auto_20170725_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransactiontruckflow',
            name='transaction',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='doniInventory.InventoryTransaction'),
            preserve_default=False,
        ),
    ]
