# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-26 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doniInventory', '0007_auto_20170725_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='doniInventory.Warehouse'),
        ),
    ]
