# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-05 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniInventory', '0008_auto_20170726_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='lots',
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='lot_no',
            field=models.CharField(default='MIX', max_length=10),
        ),
    ]
