# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_homeslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslider',
            name='call_to_action',
            field=models.TextField(default=None, null=True),
        ),
    ]
