# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_homeslider_call_to_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeslider',
            name='call_to_action',
        ),
        migrations.AddField(
            model_name='homeslider',
            name='call_to_action_text',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homeslider',
            name='call_to_action_url',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
