# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20170221_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='display_on_web',
            field=models.BooleanField(default=False),
        ),
    ]
