# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0054_currencyexchange'),
        ('website', '0009_post_visitors'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAnalyticsToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONCharField(max_length=10000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doniServer.BpBasic')),
            ],
        ),
    ]
