# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 14:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0011_auto_20170419_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleanalyticstoken',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
