# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_googleanalyticstoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleanalyticstoken',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_business', to='doniServer.BpBasic'),
        ),
    ]
