# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 10:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20170420_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleanalyticstoken',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga_token', to='doniServer.BpBasic'),
        ),
        migrations.AlterField(
            model_name='googleanalyticstoken',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ga_token_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
