# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_homeservices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeservices',
            name='image',
        ),
        migrations.AddField(
            model_name='homeservices',
            name='icon_class',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
