# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-05 11:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doniServer', '0141_transactionshipmenttracking'),
        ('doniInventory', '0009_auto_20170805_1119'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySlip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('delivery_date', models.DateField(null=True)),
                ('lot_no', models.CharField(max_length=10)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_delivery_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LocalTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity_fcl', models.FloatField(default=0.0)),
                ('quantity', models.FloatField(default=None)),
                ('price', models.FloatField(default=None)),
                ('file_id', models.CharField(max_length=100, unique=True)),
                ('contract_id', models.CharField(max_length=100, null=True)),
                ('other_info', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_local_buyer', to='doniServer.BpBasic')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_local_created_by', to=settings.AUTH_USER_MODEL)),
                ('international_file_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doniServer.Transaction')),
                ('product_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doniServer.ProductItem')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_local_seller', to='doniServer.BpBasic')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_local_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LocalTradeChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('local_trade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_log', to='doniLocalTrade.LocalTrade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_trade_changes_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'local_change_log',
            },
        ),
        migrations.CreateModel(
            name='LocalTradeNotes',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_note_created_by', to=settings.AUTH_USER_MODEL)),
                ('localTrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='doniLocalTrade.LocalTrade')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_note_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'local_notes',
            },
        ),
        migrations.CreateModel(
            name='LocalTradeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_due', models.BooleanField(default=True)),
                ('delivery_due_date', models.DateField(null=True)),
                ('delivery_done', models.BooleanField(default=False)),
                ('delivery_done_date', models.DateField(null=True)),
                ('delivery_reached', models.BooleanField(default=False)),
                ('delivery_reached_date', models.DateField(null=True)),
                ('funds_due', models.BooleanField(default=False)),
                ('funds_due_date', models.DateField(null=True)),
                ('completion_status', models.BooleanField(default=False)),
                ('completion_status_date', models.DateField(default=True)),
                ('localTrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='doniLocalTrade.LocalTrade')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance', models.BooleanField(default=False)),
                ('on_delivery_reached', models.BooleanField(default=False)),
                ('on_date', models.BooleanField(default=False)),
                ('on_date_date', models.DateField(null=True)),
                ('localTrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_terms', to='doniLocalTrade.LocalTrade')),
            ],
        ),
        migrations.AddField(
            model_name='deliveryslip',
            name='localTrade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_slip', to='doniLocalTrade.LocalTrade'),
        ),
        migrations.AddField(
            model_name='deliveryslip',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_delivery_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryslip',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doniInventory.Warehouse'),
        ),
    ]
