# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-08 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doniLocalTrade', '0002_auto_20170808_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localtradestatus',
            name='delivery_due',
        ),
        migrations.RemoveField(
            model_name='localtradestatus',
            name='localTrade',
        ),
        migrations.RemoveField(
            model_name='paymentterm',
            name='localTrade',
        ),
        migrations.AddField(
            model_name='localtradestatus',
            name='local_trade',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='doniLocalTrade.LocalTrade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentterm',
            name='local_trade',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='payment_term', to='doniLocalTrade.LocalTrade'),
            preserve_default=False,
        ),
    ]
