# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-08 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniLocalTrade', '0004_remove_localtradestatus_completion_status_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='localtradestatus',
            name='completion_status_date',
            field=models.DateField(null=True),
        ),
    ]
