# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0141_transactionshipmenttracking'),
        ('doniLocalTrade', '0006_auto_20170810_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='localtrade',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doniServer.BpBasic'),
        ),
        migrations.AlterField(
            model_name='localtrade',
            name='file_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='localtrade',
            unique_together=set([('file_id', 'business')]),
        ),
    ]
