# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-11 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doniLocalTrade', '0007_auto_20170810_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localtrade',
            name='product_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_local_product', to='doniServer.ProductItem'),
        ),
    ]
