# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-12 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doniLocalTrade', '0009_localfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localfiles',
            name='local_trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_trade_files', to='doniLocalTrade.LocalTrade'),
        ),
    ]
