# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-16 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniLocalTrade', '0010_auto_20170812_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalTradePayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_received', models.FloatField()),
                ('payment_date', models.DateField()),
            ],
            options={
                'db_table': 'local_tr_payments',
            },
        ),
        migrations.AddField(
            model_name='localtradestatus',
            name='actual_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='localtradestatus',
            name='actual_weight',
            field=models.FloatField(null=True),
        ),
    ]
