# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-19 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0143_auto_20170817_1011'),
        ('doniLocalTrade', '0011_auto_20170816_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociatedInternationalTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_international_trade', to='doniLocalTrade.LocalTrade')),
                ('transaction_associated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_with_international', to='doniServer.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='AssociatedLocalTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_local_trade', to='doniLocalTrade.LocalTrade')),
                ('local_trade_associated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_with_local', to='doniLocalTrade.LocalTrade')),
            ],
        ),
    ]
