# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-05 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doniLocalTrade', '0012_associatedinternationaltrade_associatedlocaltrade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LocalTradePayments',
            new_name='LocalTradePayment',
        ),
    ]
