# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-21 00:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import doniServer.fields.var_binary


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doniLocalTrade', '0014_remove_localtrade_international_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_dispatched', models.BooleanField(default=False)),
                ('delivery_dispatched_date', models.DateField(null=True)),
                ('delivery_reached', models.BooleanField(default=True)),
                ('delivery_reached_date', models.DateField(null=True)),
                ('actual_weight', models.FloatField(null=True)),
                ('actual_amount', models.FloatField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_delivery_details_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryWeightSlip',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=400, null=True)),
                ('file', doniServer.fields.var_binary.VarBinaryField()),
                ('extension', models.CharField(max_length=100, null=True)),
                ('weight', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_weight_slip_created_by', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_slip', to='doniLocalTrade.DeliveryDetails')),
            ],
            options={
                'db_table': 'local_delivery_weight_slips',
            },
        ),
        migrations.AlterField(
            model_name='deliveryslip',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_delivery_slip_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliveryslip',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_delivery_slip_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverydetails',
            name='delivery_slip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doniLocalTrade.DeliverySlip'),
        ),
        migrations.AddField(
            model_name='deliverydetails',
            name='local_trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_trade_delivery_detail', to='doniLocalTrade.LocalTrade'),
        ),
    ]
