from doniApi.businessPartner.bp_bank import BpBankAPI
from doniApi.businessPartner.bp_basic import BpBasicAPI, BusinessListAPI
from doniApi.businessPartner.bp_contact_numbers import BpContactNumberAPI
from doniApi.businessPartner.bp_contact_person import BpContactPersonAPI
from doniApi.businessPartner.bp_products import BpProductsAPI
from doniApi.businessPartner.bp_locations import BpLocationAPI
from doniApi.businessPartner.self import BusinessSettingsAPI
from doniApi.businessPartner.bp_report import BusinessReportAPI