# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('template', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('heading', models.TextField()),
                ('sub_heading', models.TextField()),
                ('baseTemplate', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='emailApp.EmailBase')),
            ],
        ),
    ]
