# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailmessage',
            old_name='heading',
            new_name='emailbody',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='sub_heading',
        ),
        # migrations.AlterField(
        #     model_name='emailbase',
        #     name='template',
        #     field=django_markdown.models.MarkdownField(),
        # ),
    ]
