# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 10:03
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('emailApp', '0005_auto_20170222_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailbase',
            name='template',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='body',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
