# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-13 09:56
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import doniServer.models.authentication.userProfile
import doniServer.models.businessPartner.bpProducts


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, help_text=b"If omitted, the description will be the post's title.")),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_written_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BpBank',
            fields=[
                ('acc_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_address', models.CharField(max_length=250)),
                ('bank_name', models.CharField(max_length=100)),
                ('acc_title', models.CharField(max_length=150)),
                ('acc_number', models.CharField(max_length=100)),
                ('acc_country', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'bp_bank',
            },
        ),
        migrations.CreateModel(
            name='BpBasic',
            fields=[
                ('bp_id', models.AutoField(primary_key=True, serialize=False)),
                ('bp_name', models.CharField(max_length=255, unique=True)),
                ('bp_website', models.CharField(max_length=255)),
                ('bp_credibility_index', models.IntegerField(default=1)),
                ('bp_country', models.CharField(max_length=250, null=True)),
                ('bp_address', models.TextField(blank=True, null=True)),
                ('bp_on_contract', models.BooleanField(default=False)),
                ('bp_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'bp_basic',
            },
        ),
        migrations.CreateModel(
            name='BpContact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('primary_number', models.CharField(max_length=100, null=True)),
                ('secondary_number', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('bp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doniServer.BpBasic')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp_contact_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bp_contact_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bp_contact',
            },
        ),
        migrations.CreateModel(
            name='BpContactNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_number', models.CharField(max_length=254)),
                ('type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('bp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doniServer.BpBasic')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp_contact_number_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bp_contact_number_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bp_contact_number',
            },
        ),
        migrations.CreateModel(
            name='BpEmail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None)),
                ('bp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doniServer.BpBasic')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp_emails_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bp_emails_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bp_emails',
            },
        ),
        migrations.CreateModel(
            name='BpLocation',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('bp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doniServer.BpBasic')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp_location_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bp_location_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bp_location',
            },
        ),
        migrations.CreateModel(
            name='BpProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_image', models.ImageField(blank=True, null=True, upload_to=doniServer.models.businessPartner.bpProducts.get_image_path)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('bp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doniServer.BpBasic')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp_product_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bp_product',
            },
        ),
        migrations.CreateModel(
            name='BpType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp_type_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bp_type_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('type',),
                'db_table': 'bp_type',
            },
        ),
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doniServer.BpBasic')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_type_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_type_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_type',
            },
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doniServer.BpBasic')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_type_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_type_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contact_type',
            },
        ),
        migrations.CreateModel(
            name='DashboardProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'dashboard_product',
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doniServer.BpBasic')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designation_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designation_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'designation',
            },
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'origin',
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='port_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'port',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'media/products/')),
                ('primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_image_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_images',
            },
        ),
        migrations.CreateModel(
            name='ProductKeyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keyword_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('keyword',),
                'db_table': 'product_keywords',
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_price', models.FloatField(default=0.0)),
                ('international_price', models.FloatField(default=0.0)),
                ('date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_price_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_price',
            },
        ),
        migrations.CreateModel(
            name='ProductQuality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doniServer.BpBasic')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_quality',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('business', models.ForeignKey(default=1L, on_delete=django.db.models.deletion.CASCADE, to='doniServer.BpBasic')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductsSpecification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('moisture', models.FloatField(default=None, null=True)),
                ('purity', models.FloatField(default=None, null=True)),
                ('weaveled', models.FloatField(default=None, null=True)),
                ('splits', models.FloatField(default=None, null=True)),
                ('damaged', models.FloatField(default=None, null=True)),
                ('foreignMatter', models.FloatField(default=None, null=True)),
                ('greenDamaged', models.FloatField(default=None, null=True)),
                ('otherColor', models.FloatField(default=None, null=True)),
                ('wrinkled', models.FloatField(default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specs_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_specs',
            },
        ),
        migrations.CreateModel(
            name='SecondaryTransaction',
            fields=[
                ('tr_sec_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('buyer_price', models.FloatField(default=0.0)),
                ('seller_price', models.FloatField(default=0.0)),
                ('other_info', models.TextField()),
                ('quantity', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_secondary_buyer', to='doniServer.BpBasic')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_secondary_created_by', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_secondary_seller', to='doniServer.BpBasic')),
            ],
            options={
                'db_table': 'tr_secondary',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='slug')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('tr_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('quantity', models.FloatField(default=None)),
                ('price', models.FloatField(default=None)),
                ('packing', models.CharField(max_length=50)),
                ('shipment_start', models.DateField()),
                ('shipment_end', models.DateField()),
                ('file_id', models.CharField(max_length=100, unique=True)),
                ('contract_id', models.CharField(max_length=100, null=True)),
                ('other_info', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None)),
            ],
            options={
                'db_table': 'tr_basic',
            },
        ),
        migrations.CreateModel(
            name='TransactionContractType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doniServer.BpBasic')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_type_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_type_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contract_type',
            },
        ),
        migrations.CreateModel(
            name='TransactionStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doniServer.BpBasic')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transaction_status',
            },
        ),
        migrations.CreateModel(
            name='TrFiles',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.BinaryField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_file_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tr_notes',
            },
        ),
        migrations.CreateModel(
            name='TrNote',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_note_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tr_note',
            },
        ),
        migrations.CreateModel(
            name='TrShipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_shipped', models.BooleanField(default=False)),
                ('not_shipped_reason', models.TextField()),
                ('extension', models.CharField(max_length=100)),
                ('app_received', models.BooleanField(default=False)),
                ('expected_shipment', models.DateField(default=None)),
                ('in_transit', models.DateField(default=None)),
                ('shipped', models.BooleanField(default=False)),
                ('expected_arrival', models.DateField(default=None)),
                ('transit_port', models.CharField(max_length=500, null=True)),
                ('arrived_at_port', models.BooleanField(default=False)),
                ('date_arrived', models.DateField(default=None)),
                ('actual_arrived', models.DateField(default=None)),
                ('bl_no', models.CharField(max_length=50, null=True)),
                ('invoice_no', models.CharField(max_length=50)),
                ('invoice_amount', models.FloatField(null=True)),
                ('quantity', models.FloatField(null=True)),
                ('vessel_no', models.CharField(max_length=50)),
                ('ship_line_details', models.TextField()),
                ('chk_reason', models.BooleanField(default=False)),
                ('chk_ship_ext', models.BooleanField(default=False)),
                ('chk_exp_ship', models.BooleanField(default=False)),
                ('chk_in_transit', models.BooleanField(default=False)),
                ('chk_date_shipped', models.BooleanField(default=False)),
                ('chk_expected_arrival', models.BooleanField(default=False)),
                ('chk_transit_port', models.BooleanField(default=False)),
                ('chk_date_arrived', models.BooleanField(default=False)),
                ('chk_actual_arrived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_shipment_created_by', to=settings.AUTH_USER_MODEL)),
                ('port_destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_shipment_port_destination', to='doniServer.Port')),
                ('port_loading', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_shipment_port_loading', to='doniServer.Port')),
                ('shipper_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_shipment_shipper', to='doniServer.BpBasic')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_shipment_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tr_shipment',
            },
        ),
        migrations.CreateModel(
            name='UserContactNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=100)),
                ('extension', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doniServer.BpBasic')),
                ('contact_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doniServer.ContactType')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_contact_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_contact_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_contact_number',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_profile_pic', models.ImageField(blank=True, null=True, upload_to=doniServer.models.authentication.userProfile.get_image_path)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=doniServer.models.authentication.userProfile.get_image_path)),
                ('notify_new_transaction', models.BooleanField(default=False)),
                ('notify_shipment_arrival', models.BooleanField(default=False)),
                ('notify_messages', models.BooleanField(default=False)),
                ('notify_monthly_reports', models.BooleanField(default=True)),
                ('notify_weekly_reports', models.BooleanField(default=True)),
                ('notify_daily_reports', models.BooleanField(default=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doniServer.BpBasic')),
                ('businessLocation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doniServer.BpLocation')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doniServer.Designation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'db_table': 'user_sessions',
            },
        ),
        migrations.CreateModel(
            name='TrCommission',
            fields=[
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='doniServer.Transaction')),
                ('broker_involved', models.BooleanField(default=False)),
                ('has_seller_broker', models.BooleanField(default=False)),
                ('seller_broker_comm_type', models.CharField(choices=[(b'Fixed', b'Fixed'), (b'Percentage', b'Percentage')], default=b'Fixed', max_length=50)),
                ('seller_broker_comm', models.FloatField(default=0.0)),
                ('has_buyer_broker', models.BooleanField(default=False)),
                ('buyer_broker_comm_type', models.CharField(choices=[(b'Fixed', b'Fixed'), (b'Percentage', b'Percentage')], max_length=50, null=True)),
                ('buyer_broker_comm', models.FloatField(default=0.0)),
                ('own_comm', models.FloatField(default=None)),
                ('own_comm_type', models.CharField(choices=[(b'Fixed', b'Fixed'), (b'Percentage', b'Percentage')], max_length=50, null=True)),
                ('differance', models.FloatField(default=0.0)),
                ('discount', models.FloatField(default=0.0)),
                ('net_commission', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None)),
            ],
            options={
                'db_table': 'tr_commission',
            },
        ),
        migrations.CreateModel(
            name='TrContract',
            fields=[
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='doniServer.Transaction')),
                ('doni_contract', models.BooleanField(default=False)),
                ('own_contract', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None)),
            ],
            options={
                'db_table': 'tr_contract',
            },
        ),
        migrations.CreateModel(
            name='TrStatus',
            fields=[
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='doniServer.Transaction')),
                ('status', models.CharField(choices=[(b'Washout at Par', b'WASHOUT_AT_PAR'), (b'Arrived', b'ARRIVED'), (b'Shipped', b'SHIPPED'), (b'Washout at X', b'WASHOUT_AT_X'), (b'Completed', b'COMPLETED'), (b'Not Shipped', b'NOT_SHIPPED')], default=b'Not Shipped', max_length=50)),
                ('washout_at_par', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_status_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_status_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tr_status',
            },
        ),
        migrations.AddField(
            model_name='trnote',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doniServer.Transaction'),
        ),
        migrations.AddField(
            model_name='trnote',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_note_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trfiles',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doniServer.Transaction'),
        ),
        migrations.AddField(
            model_name='trfiles',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_file_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_basic_buyer', to='doniServer.BpBasic'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_basic_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doniServer.Origin'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doniServer.Products'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='quality',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='doniServer.ProductKeyword'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_basic_seller', to='doniServer.BpBasic'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='specification',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='doniServer.ProductsSpecification'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_basic_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secondarytransaction',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doniServer.Transaction'),
        ),
        migrations.AddField(
            model_name='secondarytransaction',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_secondary_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doniServer.Products'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_price_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='doniServer.Products'),
        ),
        migrations.AddField(
            model_name='productimages',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_image_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dashboardproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doniServer.Products'),
        ),
        migrations.AddField(
            model_name='dashboardproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_product_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bpproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doniServer.Products'),
        ),
        migrations.AddField(
            model_name='bpproducts',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bp_products_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bpbasic',
            name='bp_types',
            field=models.ManyToManyField(to='doniServer.BpType'),
        ),
        migrations.AddField(
            model_name='bpbasic',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp_basic_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bpbasic',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bp_basic_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bpbank',
            name='bp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doniServer.BpBasic'),
        ),
        migrations.AddField(
            model_name='bpbank',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp_bank_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bpbank',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bp_bank_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(related_name='blog', to='doniServer.Tag'),
        ),
        migrations.AddField(
            model_name='blog',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trcontract',
            name='contractual_buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractual_buyer', to='doniServer.BpBasic'),
        ),
        migrations.AddField(
            model_name='trcontract',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_contract_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trcontract',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_contract_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trcommission',
            name='buyer_broker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_broker', to='doniServer.BpBasic'),
        ),
        migrations.AddField(
            model_name='trcommission',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_commission_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trcommission',
            name='seller_broker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_broker', to='doniServer.BpBasic'),
        ),
        migrations.AddField(
            model_name='trcommission',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_commission_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
