# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0003_auto_20161202_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='origin',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='productkeyword',
            name='keyword',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
