# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-14 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0003_auto_20170214_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsspecification',
            name='damaged',
        ),
        migrations.RemoveField(
            model_name='productsspecification',
            name='foreignMatter',
        ),
        migrations.RemoveField(
            model_name='productsspecification',
            name='greenDamaged',
        ),
        migrations.RemoveField(
            model_name='productsspecification',
            name='moisture',
        ),
        migrations.RemoveField(
            model_name='productsspecification',
            name='otherColor',
        ),
        migrations.RemoveField(
            model_name='productsspecification',
            name='purity',
        ),
        migrations.RemoveField(
            model_name='productsspecification',
            name='splits',
        ),
        migrations.RemoveField(
            model_name='productsspecification',
            name='weaveled',
        ),
        migrations.RemoveField(
            model_name='productsspecification',
            name='wrinkled',
        ),
        migrations.AddField(
            model_name='productsspecification',
            name='name',
            field=models.CharField(default=b'Product Specification', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='productsspecification',
            name='productCategory',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='doniServer.ProductCategory'),
        ),
        migrations.AddField(
            model_name='productsspecification',
            name='specs',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
