# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-14 09:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doniServer', '0004_auto_20170214_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceMarket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=250)),
                ('currency', models.CharField(max_length=20)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_market_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_market_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'price_market',
            },
        ),
        migrations.RenameField(
            model_name='productprice',
            old_name='international_price',
            new_name='price_value',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='date',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='local_price',
        ),
        migrations.AddField(
            model_name='productprice',
            name='price_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productprice',
            name='productCategory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='doniServer.ProductCategory'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='productKeywords',
            field=models.ManyToManyField(blank=True, db_constraint=False, related_name='prod_keywords', to='doniServer.ProductKeyword'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='productMarket',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='doniServer.PriceMarket'),
        ),
    ]
