# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0005_productimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(upload_to=b'media/products/'),
        ),
    ]
