# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0006_auto_20161203_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
