# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-15 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0006_auto_20170214_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('subject', models.TextField(max_length=250)),
                ('message', models.TextField(max_length=250)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=250)),
                ('is_subscribed', models.BooleanField(default=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
