# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-16 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0008_auto_20170216_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='business',
            field=models.ForeignKey(default=1L, on_delete=django.db.models.deletion.CASCADE, to='doniServer.BpBasic'),
        ),
    ]
