# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-25 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0010_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstype',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doniServer.BpBasic'),
        ),
        migrations.AddField(
            model_name='contacttype',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doniServer.BpBasic'),
        ),
        migrations.AddField(
            model_name='designation',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doniServer.BpBasic'),
        ),
        migrations.AddField(
            model_name='productquality',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doniServer.BpBasic'),
        ),
        migrations.AddField(
            model_name='transactioncontracttype',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doniServer.BpBasic'),
        ),
        migrations.AddField(
            model_name='transactionstatus',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doniServer.BpBasic'),
        ),
    ]
