# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-31 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0014_auto_20161231_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notify_messages',
            field=models.BooleanField(default=False),
        ),
    ]
