# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0016_auto_20170224_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_metric', models.CharField(choices=[(b'MT', b'mt'), (b'Kg', b'kg')], max_length=50)),
                ('price_value', models.FloatField(default=0.0)),
                ('shipment', models.DateField()),
                ('show_on_ticker', models.BooleanField(default=False)),
                ('show_on_pricing', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='product_keywords',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='product_specs_data',
        ),
        migrations.AddField(
            model_name='productprice',
            name='product_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_item_price', to='doniServer.ProductItem'),
        ),
        migrations.AddField(
            model_name='price',
            name='product_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doniServer.ProductPrice'),
        ),
    ]
