# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-14 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0018_bpbasic_bp_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='products',
            name='quality_keywords',
        ),
        migrations.RemoveField(
            model_name='products',
            name='specification',
        ),
        migrations.AddField(
            model_name='products',
            name='business',
            field=models.OneToOneField(default=1L, on_delete=django.db.models.deletion.CASCADE, to='doniServer.BpBasic'),
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
