# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0019_productkeyword_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='keywords',
            field=models.ManyToManyField(related_name='product_items', to='doniServer.ProductKeyword'),
        ),
    ]
