# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-22 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0020_auto_20170114_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='doniServer.Products'),
        ),
    ]
