# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0020_auto_20170303_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productkeyword',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='doniServer.ProductCategory'),
        ),
    ]
