# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0021_auto_20170303_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
