# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 14:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doniServer', '0022_auto_20170304_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItemPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('price_items', jsonfield.fields.JSONField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_item_price_created_by', to=settings.AUTH_USER_MODEL)),
                ('price_market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_market', to='doniServer.PriceMarket')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_product_item', to='doniServer.ProductItem')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_item_price_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-price_time',),
                'db_table': 'product_item_price',
            },
        ),
    ]
