# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0029_productitem_database_ids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productitem',
            options={'ordering': ('id',)},
        ),
    ]
