# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0030_auto_20170310_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpbasic',
            name='bp_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doniServer.BpBasic'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doniServer.BpBasic'),
        ),
        migrations.AlterField(
            model_name='products',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doniServer.BpBasic'),
        ),
    ]
