# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import doniServer.models.businessPartner.bpBasic


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0031_auto_20170310_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpbasic',
            name='bp_logo',
            field=models.ImageField(blank=True, null=True, upload_to=doniServer.models.businessPartner.bpBasic.get_image_path),
        ),
    ]
