# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0034_auto_20170310_1355'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductPriceMetric',
            new_name='PriceMetric',
        ),
        migrations.AddField(
            model_name='productitemprice',
            name='price_metric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metric_prices', to='doniServer.PriceMetric'),
        ),
    ]
