# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0035_auto_20170310_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('summary', jsonfield.fields.JSONField()),
                ('productItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='doniServer.ProductItem')),
            ],
            options={
                'ordering': ('-summary_on',),
                'db_table': 'product_price_summary',
            },
        ),
    ]
