# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0036_pricesummary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricesummary',
            old_name='productItem',
            new_name='product_item',
        ),
    ]
