# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0037_auto_20170313_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bpbasic',
            name='bp_address',
        ),
        migrations.RemoveField(
            model_name='bpbasic',
            name='bp_city',
        ),
        migrations.RemoveField(
            model_name='bpbasic',
            name='bp_country',
        ),
        migrations.RemoveField(
            model_name='bpbasic',
            name='bp_on_contract',
        ),
    ]
