# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0038_auto_20170316_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpbasic',
            name='bp_ntn',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='bpbasic',
            name='bp_name',
            field=models.CharField(max_length=255),
        ),
    ]
