# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0039_auto_20170316_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bptype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bptype',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='businesstype',
            name='business',
        ),
        migrations.RemoveField(
            model_name='contacttype',
            name='business',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='business',
        ),
        migrations.RemoveField(
            model_name='productquality',
            name='business',
        ),
        migrations.RemoveField(
            model_name='transactioncontracttype',
            name='business',
        ),
        migrations.RemoveField(
            model_name='transactionstatus',
            name='business',
        ),
        migrations.AlterField(
            model_name='bpbasic',
            name='bp_types',
            field=models.ManyToManyField(to='doniServer.BusinessType'),
        ),
        migrations.DeleteModel(
            name='BpType',
        ),
    ]
