# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0040_auto_20170318_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='bplocation',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
