# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0041_bplocation_is_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpcontact',
            name='bp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='doniServer.BpBasic'),
        ),
        migrations.AlterField(
            model_name='bplocation',
            name='bp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='doniServer.BpBasic'),
        ),
    ]
