# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0042_auto_20170320_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpcontactnumber',
            name='bp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='doniServer.BpBasic'),
        ),
    ]
