# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0045_bpbank_acc_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpbasic',
            name='bp_types',
            field=models.ManyToManyField(related_name='business', to='doniServer.BusinessType'),
        ),
    ]
