# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 08:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doniServer', '0046_auto_20170321_0724'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='doniServer.BpBasic')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifest_created_by', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='doniServer.Products')),
                ('quantity_metric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manifest_metric', to='doniServer.PriceMetric')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='doniServer.BpBasic')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manifest_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date',),
                'db_table': 'manifest_item',
            },
        ),
    ]
