# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0048_manifestitem_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestitem',
            name='quantity_metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifest_metric', to='doniServer.PriceMetric'),
        ),
    ]
