# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import doniServer.models.product.products


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0049_auto_20170321_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=doniServer.models.product.products.get_image_path),
        ),
        migrations.AlterField(
            model_name='pricemetric',
            name='metric',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
