# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0050_auto_20170322_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestitem',
            name='container_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manifestitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_manifest', to='doniServer.Products'),
        ),
    ]
