# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 12:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import doniServer.models.shipment.vessel


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doniServer', '0051_auto_20170324_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=doniServer.models.shipment.vessel.get_image_path)),
                ('imo_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=300, null=True)),
                ('broken', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=300)),
                ('nationality', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=300)),
                ('completion_year', models.CharField(max_length=100)),
                ('shipyard', models.CharField(max_length=300)),
                ('hull_number', models.CharField(max_length=100, null=True)),
                ('engine_design', models.CharField(max_length=100)),
                ('engine_type', models.CharField(max_length=100)),
                ('engine_power_output', models.CharField(max_length=100)),
                ('max_speed', models.CharField(max_length=100)),
                ('over_all_length_m', models.CharField(max_length=100)),
                ('over_all_beam_m', models.CharField(max_length=100)),
                ('max_draught_m', models.CharField(max_length=100)),
                ('max_TEU_capacity', models.CharField(max_length=100)),
                ('container_capacity_at_14t_teu', models.CharField(max_length=100)),
                ('reefer_containers_TEU', models.CharField(max_length=100)),
                ('dead_weight_ton', models.CharField(max_length=100)),
                ('gross_tonnage_ton', models.CharField(max_length=100)),
                ('handling_gear', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vessel_created_by', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doniServer.BpBasic')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vessel_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
