# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0052_vessel'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='on_website',
            field=models.BooleanField(default=False),
        ),
    ]
