# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0054_currencyexchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='price_on_website',
            field=models.BooleanField(default=False),
        ),
    ]
