# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0056_pricemetric_kgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricemetric',
            name='kgs',
            field=models.IntegerField(),
        ),
    ]
