# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0057_auto_20170424_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricemetric',
            name='kgs',
            field=models.IntegerField(null=True),
        ),
    ]
