# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0058_auto_20170424_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='import_expense',
            field=models.FloatField(default=1.07),
        ),
    ]
