# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 10:53
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0062_commissiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='specification',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
