# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0063_productitem_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsspecification',
            name='productCategory',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='doniServer.ProductCategory'),
        ),
    ]
