# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0064_auto_20170506_0705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trcommission',
            old_name='own_comm',
            new_name='commission',
        ),
        migrations.RenameField(
            model_name='trcommission',
            old_name='differance',
            new_name='difference',
        ),
        migrations.RemoveField(
            model_name='trcommission',
            name='broker_involved',
        ),
        migrations.RemoveField(
            model_name='trcommission',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='trcommission',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='trcommission',
            name='has_buyer_broker',
        ),
        migrations.RemoveField(
            model_name='trcommission',
            name='has_seller_broker',
        ),
        migrations.RemoveField(
            model_name='trcommission',
            name='own_comm_type',
        ),
        migrations.RemoveField(
            model_name='trcommission',
            name='seller_broker_comm',
        ),
        migrations.RemoveField(
            model_name='trcommission',
            name='seller_broker_comm_type',
        ),
        migrations.RemoveField(
            model_name='trcommission',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='trcommission',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='trcommission',
            name='commission_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_commission_type', to='doniServer.CommissionType'),
        ),
        migrations.AlterField(
            model_name='trcommission',
            name='buyer_broker_comm_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_broker_commission_type', to='doniServer.CommissionType'),
        ),
    ]
