# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0065_auto_20170512_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='packing',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='product',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='specification',
        ),
        migrations.AddField(
            model_name='transaction',
            name='contractual_buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_contractual_buyer', to='doniServer.BpBasic'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='packaging',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doniServer.Packaging'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='product_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doniServer.ProductItem'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='product_specification',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
