# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0066_auto_20170513_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
