# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0068_auto_20170513_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trnote',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
