# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0069_auto_20170515_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trnote',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='doniServer.Transaction'),
        ),
    ]
