# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0070_auto_20170515_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='related_products',
            field=models.ManyToManyField(blank=True, null=True, related_name='_products_related_products_+', to='doniServer.Products'),
        ),
    ]
