# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 14:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import doniServer.models.shipment.shippingLine


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doniServer', '0071_products_related_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('website', models.CharField(max_length=300, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=doniServer.models.shipment.shippingLine.get_image_path)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_line_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_line_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
