# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0073_auto_20170520_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='price_on_website_order',
            field=models.IntegerField(default=100),
        ),
    ]
