# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-26 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0075_auto_20170526_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='trfiles',
            name='extension',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
