# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-03 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0076_trfiles_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='trfiles',
            name='file_name',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
