# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-03 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0077_trfiles_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trfiles',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='trfiles',
            name='updated_by',
        ),
    ]
