# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 12:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doniServer', '0079_auto_20170603_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('lo_code', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship_port_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ship_port_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='port',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='port',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='trshipment',
            name='port_destination',
        ),
        migrations.RemoveField(
            model_name='trshipment',
            name='port_loading',
        ),
        migrations.DeleteModel(
            name='Port',
        ),
    ]
