# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0080_auto_20170607_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='trshipment',
            name='port_destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_shipment_port_destination', to='doniServer.ShippingPort'),
        ),
        migrations.AddField(
            model_name='trshipment',
            name='port_loading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_shipment_port_loading', to='doniServer.ShippingPort'),
        ),
    ]
