# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0081_auto_20170608_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingport',
            name='contact_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shippingport',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shippingport',
            name='website',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
