# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0082_auto_20170614_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingport',
            name='lo_code',
            field=models.CharField(max_length=200),
        ),
    ]
