# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0083_auto_20170614_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingport',
            name='lo_code',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='imo_number',
            field=models.CharField(max_length=20),
        ),
    ]
