# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-15 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0084_auto_20170614_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpbasic',
            name='bp_database_id',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='business',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='doniServer.BpBasic'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='business',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='doniServer.BpBasic'),
        ),
        migrations.AlterField(
            model_name='products',
            name='business',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='doniServer.BpBasic'),
        ),
    ]
