# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0088_auto_20170704_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trshipment',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
