# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 20:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doniServer', '0090_auto_20170704_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('transaction', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changeLog', to='doniServer.Transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_changes_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tr_change_log',
            },
        ),
    ]
