# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0092_auto_20170704_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
