# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-06 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0093_transaction_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_washout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_washout_at',
            field=models.FloatField(default=0.0),
        ),
    ]
