# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-07 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0094_auto_20170706_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingline',
            name='tracking_website',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
