# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-07 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0095_shippingline_tracking_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='trcommission',
            name='quantity_commission',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vessel',
            name='mmsi_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='shipping_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vessels', to='doniServer.ShippingLine'),
        ),
    ]
