# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-07 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0096_auto_20170707_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_type_receivable', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('amount', models.FloatField(default=0.0)),
                ('received', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_flow', to='doniServer.BpBasic')),
                ('international_trade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_commission_flow', to='doniServer.Transaction')),
            ],
            options={
                'db_table': 'commission_flow',
            },
        ),
    ]
