# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-10 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0097_commissionflow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trshipment',
            old_name='shipper_id',
            new_name='shipper',
        ),
        migrations.AddField(
            model_name='trshipment',
            name='date_shipped_on',
            field=models.DateField(default=None, null=True),
        ),
    ]
