# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-10 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0098_auto_20170710_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trshipment',
            name='ship_line_details',
        ),
        migrations.AddField(
            model_name='trshipment',
            name='shipping_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_shipments', to='doniServer.ShippingLine'),
        ),
    ]
