# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-10 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0099_auto_20170710_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='trcommission',
            name='earned_commission',
            field=models.FloatField(default=0.0),
        ),
    ]
