# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-12 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0100_trcommission_earned_commission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_washout',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_washout_at',
        ),
    ]
