# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-12 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0101_auto_20170712_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrWashout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_commission_payable', models.BooleanField(default=True)),
                ('washout_date', models.DateField()),
                ('washout_due_date', models.DateField()),
                ('is_washout', models.BooleanField(default=False)),
                ('is_washout_at', models.FloatField(default=0.0)),
                ('buyer_washout_price', models.FloatField(default=0.0)),
                ('seller_washout_price', models.FloatField(default=0.0)),
                ('broker_difference', models.FloatField(default=0.0)),
                ('total_difference', models.FloatField(default=0.0)),
                ('washout_commission', models.FloatField(default=0.0)),
                ('transaction', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='washout', to='doniServer.Transaction')),
            ],
            options={
                'db_table': 'tr_washout',
            },
        ),
    ]
