# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-13 09:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doniServer', '0103_remove_trwashout_is_washout_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='trwashout',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trwashout',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_washout_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trwashout',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='trwashout',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_washout_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
