# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-13 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0104_auto_20170713_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trwashout',
            name='washout_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='trwashout',
            name='washout_due_date',
            field=models.DateField(null=True),
        ),
    ]
