# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-14 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0106_expensetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAppProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=20)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to='doniServer.BpBasic')),
            ],
            options={
                'db_table': 'business_profile',
            },
        ),
        migrations.AddField(
            model_name='expensetype',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expensetype',
            name='default_order',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
