# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-14 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0108_inttradeinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessappprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
