# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-14 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0109_businessappprofile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessappprofile',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_profile', to='doniServer.BpBasic'),
        ),
    ]
