# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-15 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0111_auto_20170714_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trcommission',
            old_name='quantity_commission',
            new_name='buyer_commission_actual',
        ),
        migrations.AddField(
            model_name='trcommission',
            name='buyer_commission_expected',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trcommission',
            name='quantity_shipped',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trcommission',
            name='seller_commission_actual',
            field=models.FloatField(default=0.0),
        ),
    ]
