# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-15 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0113_auto_20170715_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='trcommission',
            name='seller_commission_expected',
            field=models.FloatField(default=0.0),
        ),
    ]
