# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-17 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0114_trcommission_seller_commission_expected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trfiles',
            name='extension',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
