# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-18 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0117_auto_20170717_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trshipment',
            name='vessel_no',
        ),
        migrations.AddField(
            model_name='trshipment',
            name='vessel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_shipment_vessel', to='doniServer.Vessel'),
        ),
    ]
