# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-18 10:36
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0118_auto_20170718_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trshipment',
            name='transit_port',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
