# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-18 19:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doniServer', '0120_remove_transaction_is_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrComplete',
            fields=[
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='completion_status', serialize=False, to='doniServer.Transaction')),
                ('is_complete', models.BooleanField(default=False)),
                ('completion_date', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_complete_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_complete_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tr_complete',
            },
        ),
    ]
