# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-19 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0122_auto_20170719_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trshipment',
            name='extension',
            field=models.DateField(max_length=100),
        ),
    ]
