# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-19 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0123_auto_20170719_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trshipment',
            name='extension',
            field=models.DateField(default=None, null=True),
        ),
    ]
