# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-20 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0124_auto_20170719_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inttradeinvoice',
            old_name='invoice_obj',
            new_name='invoice_items',
        ),
        migrations.AddField(
            model_name='inttradeinvoice',
            name='currency_rate',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
