# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-20 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0125_auto_20170720_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='inttradeinvoice',
            name='invoice_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='doniServer.BpBasic'),
            preserve_default=False,
        ),
    ]
