# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-20 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0126_inttradeinvoice_invoice_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='TAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('debit', models.BooleanField(default=False)),
                ('credit', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('code', models.IntegerField()),
                ('amount', models.FloatField(default=0.0)),
                ('is_due', models.BooleanField(default=False)),
                ('received', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_account', to='doniServer.BpBasic')),
                ('business_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_account', to='doniServer.BpBasic')),
                ('int_invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_t_accounts', to='doniServer.IntTradeInvoice', unique=True)),
                ('international_trade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_commission_flow', to='doniServer.Transaction')),
            ],
            options={
                'db_table': 't_accounts',
            },
        ),
        migrations.RemoveField(
            model_name='commissionflow',
            name='business',
        ),
        migrations.RemoveField(
            model_name='commissionflow',
            name='international_trade',
        ),
        migrations.DeleteModel(
            name='CommissionFlow',
        ),
    ]
