# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-21 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0128_businessappprofile_other_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpbasic',
            name='bp_database_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
