# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0129_auto_20170721_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrSellerInvoice',
            fields=[
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='seller_invoice', serialize=False, to='doniServer.Transaction')),
                ('tr_seller_invoice_no', models.CharField(max_length=50)),
                ('tr_seller_invoice_amount_usd', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'tr_seller_invoice',
            },
        ),
    ]
