# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-28 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0130_trsellerinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='has_secondary_trades',
            field=models.BooleanField(default=False),
        ),
    ]
