# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-28 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0131_transaction_has_secondary_trades'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'transaction_primary_trades',
            },
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='has_secondary_trades',
        ),
        migrations.AddField(
            model_name='primarytrade',
            name='primary_trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_trade', to='doniServer.Transaction'),
        ),
        migrations.AddField(
            model_name='primarytrade',
            name='transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_trade', to='doniServer.Transaction'),
        ),
    ]
