# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-28 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0132_auto_20170728_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='inttradeinvoice',
            name='weight_in_mt',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
