# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-31 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0133_inttradeinvoice_weight_in_mt'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorigin',
            name='country_flag',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productorigin',
            name='country_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='right_business_analytics',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='right_business_commission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='right_user_management',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='right_warehouse_module',
            field=models.BooleanField(default=False),
        ),
    ]
