# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-31 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0134_auto_20170731_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='bplocation',
            name='country_flag',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bplocation',
            name='country_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
