# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-02 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0137_auto_20170802_0815'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SeacondaryTrades',
            new_name='SecondaryTrades',
        ),
        migrations.AddField(
            model_name='trshipment',
            name='voyage_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
