# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-02 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0138_auto_20170802_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trshipment',
            old_name='container_no',
            new_name='containers',
        ),
    ]
