# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-02 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0139_auto_20170802_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='imo_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
