# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-17 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0142_tradedispute'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradedispute',
            name='details',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradedispute',
            name='dispute_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradedispute',
            name='dispute_resolved_date',
            field=models.DateField(null=True),
        ),
    ]
