# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-20 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doniServer', '0143_auto_20170817_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trsellerinvoice',
            name='tr_seller_invoice_amount_usd',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='trsellerinvoice',
            name='tr_seller_invoice_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
